[package]
name = "citadel-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
citadel-irparser = { git = "https://github.com/Isible/citadel.git" }
citadel-api = { git = "https://github.com/Isible/citadel.git" }
bumpalo = "3.16.0"
